export const data = [
  { item: "sweet", imgUrl: "sweet-1.jpeg", price: "5" },
  { item: "cupcake", imgUrl: "cupcake-1.jpeg", price: "5" },
  { item: "cake", imgUrl: "cake-1.jpeg", price: "5" },
  { item: "doughnut", imgUrl: "doughnut-1.jpeg", price: "5" },
  { item: "sweet", imgUrl: "sweet-2.jpeg", price: "10" },
  { item: "cupcake", imgUrl: "cupcake-2.jpeg", price: "10" },
  { item: "cake", imgUrl: "cake-2.jpeg", price: "10" },
  { item: "doughnut", imgUrl: "doughnut-2.jpeg", price: "10" },
  { item: "sweet", imgUrl: "sweet-3.jpeg", price: "15" },
  { item: "cupcake", imgUrl: "cupcake-3.jpeg", price: "15" },
  { item: "cake", imgUrl: "cake-3.jpeg", price: "15" },
  { item: "doughnut", imgUrl: "doughnut-3.jpeg", price: "15" },
  {},
];
